# Generated by Django 4.1 on 2022-08-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_alter_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='views',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
