# Generated by Django 4.1 on 2022-08-17 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_rename_master_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comment_video', to='video.comment'),
        ),
    ]
