# Generated by Django 4.1 on 2022-08-17 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_video_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='comments',
        ),
    ]
